config/routes.rb
Rails.application.routes.draw do
   devise_for :admins,:path => "admin", controllers: {
        sessions: 'admin/sessions',
        passwords:  'admin/passwords',
        registrations: 'admin/registrations'
      }

 get '/admin' => 'admin/homes#top'
     namespace :admin do
       resources :genres
       resources :items
       resources :customers
       resources :orders,only:[:index,:show,:update]
       resources :order_details,only:[:update]
     end
     root to: 'public/homes#top'
     get '/about' => 'public/homes#about'
    scope module: :public do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
      resources :items, only:[:index,:show,:new] do
      end
      resources :cart_items
      post '/orders/session' => 'orders#session_create'
      get '/orders/confirm' => 'orders#confirm'
      post '/orders/confirm' => 'orders#confirm'
      get '/orders/thanks' => 'orders#thanks'
      patch '/customers/is_active' => 'customers#destroy'
      get '/customers/is_active' => 'customers#quit'
      get '/customers/my_page' => 'customers#show'
      resources :orders, only:[:new,:create,:index,:show]
      resource :customers, only:[:edit,:update]
      resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
      }
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
    	# アソシエーション
  belongs_to :customer

  # バリデーション
  validates :postal_code, :address, :name, presence: true


	def address_all
    self.postal_code+" "+self.address+" "+self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  enum is_active: {Available: true, Invalid: false}
    #有効会員はtrue、退会済み会員はfalse

    def active_for_authentication?
        super && (self.is_active === "Available")
    end
    #is_activeが有効の場合は有効会員(ログイン可能)


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items


	validates :name, presence: true #
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
	has_many :order_details
	belongs_to :genre


  # バリデーション
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    	# アソシエーション
  belongs_to :customer
	has_many :order_details
	enum payment: {銀行振込:0, クレジットカード:1}

  # enum設定
	enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum maiking_status: [:着手不可,:製作待ち,:製作中,:製作完了]

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!


  def top
  	@orders = Order.all
  end

  def index
  		@orders = Order.all
  end

  def current_index
    @orders = Order.all
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.all
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
  	if @item.save
  	   redirect_to admin_item_path(@item)
  	else
  	   render "new"
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  	  redirect_to admin_item_path(@item.id)
  	else
  		render "edit"
  	end
  end


  private

  def item_params
  	params.require(:item).permit(:genre_id,:name,:price,:is_active,:introduction,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    #before_action :authenticate_admin!
  def index
    @path = Rails.application.routes.recognize_path(request.referer)
    if @path[:controller] == "admin/customers" && @path[:action] == "show"
       @order = Order.where(customer_id: params[:format])
    elsif @path[:controller] == "admin/admins"
       @order = Order.where(created_at: Time.zone.today.all_day)
    else
       @order = Order.all
    end
  end


  def show
  	@order = Order.find(params[:id])
  	@order_details = @order.order_details
  end

  def update
  	@order = Order.find(params[:id]) #注文詳細の特定
  	@order_details = @order.order_details #注文から紐付く商品の取得
  	@order.update(order_params) #注文ステータスの更新


 	if @order.status == "入金確認" #注文ステータスが入金確認なら下の事をする
	     @order_details.update_all(maiking_status: 1) #製作ステータスを「製作待ちに」　更新
	     end
  		 redirect_to  admin_order_path(@order) #注文詳細に遷移
    end


  private

  def order_params
  	params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    
    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

    def after_sign_up_path_for(resource)
      case resource
      when Admin
      admin_items_path
      when Customer
      customers_my_page_path
      end
    end


    def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end



	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/orders/show.html.erb
<div class="container takasa">
  <div class="row">
    <div class="col-xs-12">
      <h2>注文履歴詳細</h2>
      <!-- 購入詳細情報 -->
      <table>
       <tr>
        <th class= "order-show">購入者</th>
        <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>
      <tr>
        <th class= "order-show">注文日</th>
        <td><%= @order.created_at %></td>
      </tr>
      </tr>
      <tr>
        <th class= "order-show">配送先</th>
        <td>〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></td>
      </tr>
      <tr>
        <th class= "order-show">支払い方法</th>
        <td><%= @order.payment %></td>
      </tr>
      <tr>

        <th>注文ステータス</th>
        <td>
          <%= form_for @order, url: admin_order_path do |f| %><!--oreder controllerのupdateの飛ぶ-->
          　<%= f.select :status,["入金待ち","入金確認","製作中","発送準備中","発送済"] ,style: "margin-top:10px;#" %><!--ステータス選択 -->
          <%= f.submit "更新" ,class: "btn btn-primary btn-sm" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="orders-show">
    <div class=" col-xs-9">
      <table class="table ">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
        <%  @order_details.each do |order_detail| %><!--注文した商品の履歴一覧をeach分で表示　-->
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= ((order_detail.price)*(order_detail.amount)) %> </td>

          <%= form_for order_detail,url: admin_order_detail_path(order_detail.id) do |f| %>
          <td><%= f.select :maiking_status,["着手不可","製作待ち","製作中","製作完了"] %></td><!--ステータス選択 -->
          <td><%= f.submit "更新" ,class:"btn btn-primary btn-xs" %></td>
          <% end %>
        </tr>
          <% end %>
      </table>
    </div>


    <div class="total">
     <h4>商品合計     <%= @order.total_price %>円</h4>
     <h4>送料　　　    <%= @order.postage %>円</h4>
     <h4>請求金額合計　<%= (@order.total_price+@order.postage) %>円</h4>
    </div>
  </div>

</div>