config/routes.rb
Rails.application.routes.draw do
   devise_for :admins,:path => "admin", controllers: {
        sessions: 'admin/sessions',
        passwords:  'admin/passwords',
        registrations: 'admin/registrations'
      }

 get '/admin' => 'admin/homes#top'
     namespace :admin do
       resources :genres
       resources :items
       resources :customers
       resources :orders,only:[:index,:show,:update]
       resources :order_details,only:[:update]
     end
     root to: 'public/homes#top'
     get '/about' => 'public/homes#about'
    scope module: :public do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
      resources :items, only:[:index,:show,:new] do
      end
      resources :cart_items
      post '/orders/session' => 'orders#session_create'
      get '/orders/confirm' => 'orders#confirm'
      post '/orders/confirm' => 'orders#confirm'
      get '/orders/thanks' => 'orders#thanks'
      patch '/customers/is_active' => 'customers#destroy'
      get '/customers/is_active' => 'customers#quit'
      get '/customers/my_page' => 'customers#show'
      resources :orders, only:[:new,:create,:index,:show]
      resource :customers, only:[:edit,:update]
      resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
      }
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
    	# アソシエーション
  belongs_to :customer

  # バリデーション
  validates :postal_code, :address, :name, presence: true


	def address_all
    self.postal_code+" "+self.address+" "+self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  enum is_active: {Available: true, Invalid: false}
    #有効会員はtrue、退会済み会員はfalse

    def active_for_authentication?
        super && (self.is_active === "Available")
    end
    #is_activeが有効の場合は有効会員(ログイン可能)


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items


	validates :name, presence: true #
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
	has_many :order_details
	belongs_to :genre


  # バリデーション
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    	# アソシエーション
  belongs_to :customer
	has_many :order_details
	enum payment: {銀行振込:0, クレジットカード:1}

  # enum設定
	enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum maiking_status: [:着手不可,:製作待ち,:製作中,:製作完了]

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!


  def top
  	@orders = Order.all
  end

  def index
  		@orders = Order.all
  end

  def current_index
    @orders = Order.all
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.all
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
  	if @item.save
  	   redirect_to admin_item_path(@item)
  	else
  	   render "new"
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  	  redirect_to admin_item_path(@item.id)
  	else
  		render "edit"
  	end
  end


  private

  def item_params
  	params.require(:item).permit(:genre_id,:name,:price,:is_active,:introduction,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    
    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

    def after_sign_up_path_for(resource)
      case resource
      when Admin
      admin_items_path
      when Customer
      customers_my_page_path
      end
    end


    def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end



	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container takasa">
  <div class="row">

    <div class="col-xs-9">
      <h2>ジャンル編集</h2><br>


       <%= form_for @genre, url: admin_genre_path(@genre.id) do |f| %>
        <div class="field row">
          <lavel>ジャンル名</lavel>
          <%= f.text_field :name %>
          <%= f.submit "変更を保存する", class: "btn btn-primary" %>
         </div>
      <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container takasa ">
  <div class="row ">

    <h2>ジャンル一覧・追加</h2><br>

    <%= form_for @genre, url: admin_genres_path do |f| %>
    <div class="text-right">
      <lavel>ジャンル名</lavel>
      <%= f.text_field :name %>
      <%= f.submit "新規登録", class: "btn btn-primary" %>
    </div>
    <% end %>
    <br>
    <!-- ジャンル一覧 -->
    <table class = "table table-hover">
      <thead>
        <tr class="active">
          <th>ジャンル</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td class="text-left"><%= genre.name%></td>
            <td class="genre-td"><%= link_to "編集する", edit_admin_genre_path(genre), class: "glyphicon glyphicon-pencil btn btn-success" %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/homes/top.html.erb
<h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<table class="table table-hover table-bordered table-condensed">
		  <thead>
		    <tr class="info">
		      <th class="col-md-3"><i class="far fa-clock"></i>購入日時</th>
	      	  <th><i class="far fa-user"></i>購入者</th>
		      <th class="col-md-1">注文個数</th>
		      <th class="col-md-2">注文ステータス</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @orders.each do |order| %>
		      <tr>
		        <td>
		          <%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
		          	<%= order.created_at %>
		          <% end %>
		        </td>
		        <td class="text-left">
		         <%= order.customer.first_name %> <%= order.customer.last_name %>
		          </td>
		        <td class="text-right">
		          <%= order.order_details.count %>
		        </td>
    	        <td>
    	      	  <%= order.status %>
     	        </td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
    </div>

app/views/admin/items/edit.html.erb
<div class="container takasa">

  <h2 class="edit-title">商品編集</h2>

  <%= form_for @item,url: {action: "update"} do |f| %>
  <div class="row">
    <div class="col-xs-4">
      <label>商品画像</label>
      <%= f.attachment_field :image %>
    </div>
    <div class="col-xs-8">
      <h4 class="edit-sukima">
        <%= f.label :"商品名" ,class: "col-xs-3" %>
        <%= f.text_field :name, class: "col-xs-8 " %>
      </h4><br>
      <h4 class="edit-sukima">
        <%= f.label :"商品説明" ,class: "col-xs-3"%>
        <%= f.text_area :introduction,size: "20*20", class: "col-xs-8" %>
      </h4>
      <h4 class="edit-sukima">
        <%= f.label :"ジャンル" ,class: "col-xs-3 "%>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </h4>
      <h4 class="edit-sukima">
        <%= f.label :"税別価格" ,class: "col-xs-3"%>
        <%= f.text_field :price, class: "col-xs-5"%>円<br>
      </h4>
      <h4 class="edit-sukima">
        <%= f.label :"販売ステータス" ,class: "col-xs-3" %>
        <%= f.select :is_active,{'販売中':true, '販売停止':false} ,class: "col-xs-8"%>
      </h4>
      <div class="text-right"><%= f.submit :変更を保存, class: "btn btn-primary" %><div>
        <% end %>
      </div>
    </div>
  </div>

app/views/admin/items/index.html.erb
<div class="container takasa">

  <h2>商品一覧</h2>

  <div class="text-right index-new">
    <%= link_to new_admin_item_path, data: {"turbolinks" => false} do %>
      <button type="button" class="btn btn-success btn-success btn-circle btn-lg">＋</button>
    <% end %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr class="active">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td><% if item.is_active == true %>
      					<p><i class="fas fa-bullseye red"></i>販売中</p>
      				<% elsif item.is_active == false %>
      					<p><i class="fas fa-bullseye blue"></i>販売停止中</p>
      				<% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>

app/views/admin/items/new.html.erb
<div class="container takasa">
  <div class="row row-new">

    <h2>商品新規登録</h2><br>

    <!-- 画像選択欄 -->
    <div class="col-xs-4">
      <%= form_for(@item, url:admin_items_path) do |f| %>

      <div class="item-image">
      </div><br>

      <%= f.attachment_field :image, placeholder: "商品画像" %>

    </div>

    <!-- 商品登録フォーム -->
    <div class="col-xs-8">
        <div class="new-field">
          <h4><%= f.label :商品名 ,class: "col-xs-3" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "item_name" ,class: "col-xs-8"%></h4>
        </div>
        <div class="new-field">
          <h4><%= f.label :商品説明 ,class: "col-xs-3" %>
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" ,class: "col-xs-8"%></h4>
        </div>
        <div class="new-field">
          <h4><%= f.label :ジャンル ,class: "col-xs-3 fix" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name %></h4>

        </div>
        <div class="new-field">
          <h4><%= f.label :税抜価格 ,class: "col-xs-3 block"  %>
          <%= f.text_field :price, autofocus: true, autocomplete: "price" ,class: "col-xs-8"%></h4>
        </div>
        <div class="new-field">
          <h4><%= f.label :販売ステータス  ,class: "col-xs-3 fix" %>
          <%= f.select :is_active,  {'販売中':true, '販売停止':false} ,class: "btn btn-primary"%></h4>
        </div>
        <div class="text-right"><%= f.submit "新規登録" ,class: "btn btn-primary"%></div>
        <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container takasa">
  <h2>商品詳細</h2><br>
  <div class="row">
    <!-- 画像選択欄 -->
    <div class="col-xs-4">
      <%= attachment_image_tag @item, :image, size:"300*300" ,  fallback: "noimage.png"%><br>
      <br>
    </div>

    <!-- 商品登録フォーム -->
    <div class="col-xs-8">
      <h4 style="margin-bottom: 30px;">商品名
        <%= @item.name %>
      </h4>

      <div style="display: flex;">
        <h4 style="margin: 0 30px 30px 0;">商品説明</h4>
        <div style="overflow-wrap: break-word;　word-wrap: break-word; width: 300px;">
          <%= @item.introduction %>
        </div>
      </div>

        <h4 style="margin-bottom: 30px;">ジャンル
          <%= @item.genre.name %>
        </h4>

        <h4 style="margin-bottom: 30px;">税込価格<%= @item.price %>
	        								<%= (@item.price*1.1).to_i %> 円<br>
						(税抜価格)
        </h4>

        <h4 style="margin-bottom: 30px;">販売ステータス
        <% if @item.is_active == true %>
        販売中
        <% else %>
        販売停止
        <% end %>

        </h4>

        <%= button_to '編集する',edit_admin_item_path(@item.id), method: :get ,class: "btn btn-primary ", style: "margin-left:70%;"%>
    </div>
  </div>
</div>