config/routes.rb
Rails.application.routes.draw do
   devise_for :admins,:path => "admin", controllers: {
        sessions: 'admin/sessions',
        passwords:  'admin/passwords',
        registrations: 'admin/registrations'
      }

 get '/admin' => 'admin/homes#top'
     namespace :admin do
       resources :genres
       resources :items
       resources :customers
       resources :orders,only:[:index,:show,:update]
       resources :order_details,only:[:update]
     end
     root to: 'public/homes#top'
     get '/about' => 'public/homes#about'
    scope module: :public do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
      resources :items, only:[:index,:show,:new] do
      end
      resources :cart_items
      post '/orders/session' => 'orders#session_create'
      get '/orders/confirm' => 'orders#confirm'
      post '/orders/confirm' => 'orders#confirm'
      get '/orders/thanks' => 'orders#thanks'
      patch '/customers/is_active' => 'customers#destroy'
      get '/customers/is_active' => 'customers#quit'
      get '/customers/my_page' => 'customers#show'
      resources :orders, only:[:new,:create,:index,:show]
      resource :customers, only:[:edit,:update]
      resources :addresses, only:[:index, :edit, :destroy, :create, :update]
  end
  devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
      }
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
    	# アソシエーション
  belongs_to :customer

  # バリデーション
  validates :postal_code, :address, :name, presence: true


	def address_all
    self.postal_code+" "+self.address+" "+self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cart_items
  has_many :addresses
  has_many :orders
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  enum is_active: {Available: true, Invalid: false}
    #有効会員はtrue、退会済み会員はfalse

    def active_for_authentication?
        super && (self.is_active === "Available")
    end
    #is_activeが有効の場合は有効会員(ログイン可能)


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items


	validates :name, presence: true #
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
	has_many :order_details
	belongs_to :genre


  # バリデーション
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    	# アソシエーション
  belongs_to :customer
	has_many :order_details
	enum payment: {銀行振込:0, クレジットカード:1}

  # enum設定
	enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
	belongs_to :item
	enum maiking_status: [:着手不可,:製作待ち,:製作中,:製作完了]

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
     before_action :authenticate_admin!


  def top
  	@orders = Order.all
  end

  def index
  		@orders = Order.all
  end

  def current_index
    @orders = Order.all
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.all
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    
    def after_sign_in_path_for(resource)
      case resource
      when Admin
      admin_path
      when Customer
      root_path
      end
    end

    def after_sign_up_path_for(resource)
      case resource
      when Admin
      admin_items_path
      when Customer
      customers_my_page_path
      end
    end


    def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end



	protected

	def configure_permitted_parameters
		added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :password_confirmation ]

		devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
	end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="text-success">NaganoCake</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5c442e0d91.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbolinks="false">
    <div id="wrapper">
        <header>
          <nav class="navbar navbar-expand-lg">
          <div class="container">
            <a class="navbar-left">
            <%= link_to root_path do %>
                 <%= image_tag "noimage.png", :size =>'80x80' %>
              <% end %>
            </a>
            <nav>
              <ul class="navbar-nav ml-auto">
                <!-- 会員でログインしている時 -->
                <% if customer_signed_in? %>
                  <li id="youkoso">ようこそ、<%= current_customer.last_name %>さん！</li>
                  <li><%= link_to customers_my_page_path do %><i class="fas fa-user"></i>マイページ<% end %></li>
                  <li><%= link_to items_path do %><i class="fas fa-cookie-bite"></i>商品一覧<% end %></li>
                  <li><%= link_to cart_items_path do %><div class="icon-flex"><i class="icon-count text-center"></i></div><i class="fas fa-shopping-cart"></i>カート</i><% end %></li>
                  <li><%= link_to destroy_customer_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
                  <li><input name="search" placeholder="search　🔍"></li>
                <!-- 管理者でログインしている時 -->
                <% elsif admin_signed_in?%>
                  <li><%= link_to ' 商品一覧', admin_items_path %></li>
                  <li><%= link_to ' 会員一覧', admin_customers_path %></li>
                  <li><%= link_to ' 注文履歴一覧', admin_path %></li>
                  <li><%= link_to ' ジャンル一覧', admin_genres_path %></li>
                  <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete %></li>
                  <li><input name="search" placeholder="search　🔍"></li>
                <!-- ログインしていない時 -->
                <% else %>
                  <li><%= link_to about_path do %><i class="fas fa-building"></i>About<% end %></li>
                  <li><%= link_to items_path do %><i class="fas fa-cookie-bite"></i>商品一覧<% end %></li>
                  <li><%= link_to new_customer_registration_path do %><i class="fas fa-user-plus"></i>新規登録<% end %></li>
                  <li><%= link_to new_customer_session_path do %><i class="fas fa-sign-in-alt"></i>ログイン<% end %></li>
                  <li><input name="search" placeholder="search　🔍"></li>
                <% end %>
              </ul>
            </nav>
          </div>
          </nav>
        </header>

        <main id="content">
          <%= yield %>
        </main>
    </div>
  </body>
</html>